### ISSUE TITLE
Enabling speech bubbles is broken after the TTF change.

### ISSUE THREAD

**Issue by pjbroad** [raduprv/Eternal-Lands#90] opened 2020-11-29 03:13 UTC
ALT+O enables speech bubbles over your character for local your chat.

However, since the TTF change:
* The text is not display correctly, looking truncated.
* The first bubble message switches the "Name" font back to font 0.

While bubble background is also not displayed correctly, this is broken before the TTF change.

In draw_ingame_string() in font.h, the chat font is used where the name font should perhaps be specified.  If this is changed, the name font is still reset to font 0, but the text does now display.

The problem appears to be that the calculated font size is too small and this triggers the font reset in the FontManager::get() function.  I've so far failed to find a fix.  Perhaps @gvissers, you could take a look?

**Comment by gvissers** [comment] 2020-11-29 09:04
Will have a look, might be a few days, however. As this is probably the most unloved feature in EL, I don't think speed is much of, though :)

**Comment by gvissers** [comment] 2020-12-01 19:41
After staring at the `draw_actor_overtext()` and `draw_ingame_string()` for an hour and trying to figure out the coordinate system, I decided that trying to draw text in world coordinates is utter madness. I also think the perspective view on the text looked rather strange. Since most of the banner was already drawn in orthographic coordinates already, I simply moved the speech bubbles up a bit into that code block, and scrapped draw_ingame_string() altogether. The coordinates need some fine tuning still: the speech bubbles overlap the names, the margin should be a bit smaller and should depend on the line height, not the maximum character width, but I got the basic feature working:
![speech_bubble](https://user-images.githubusercontent.com/1096355/100787939-ad838500-3414-11eb-8ecb-9d1af6b54afe.png)
The reason the bubble itself was not drawn was interesting: the winding direction of the polygon was wrong. Now, I distinctly remember seeing the speech bubbles before (a long, long time ago), but if this ever worked with how it was coded in the current tree, it must have been entirely by accident.

**Comment by pjbroad** [comment] 2020-12-01 22:51
I feel much better now that I could not work out how to fix the previous code either, I also considered just using a more standard approach so I think that's fine.  Interesting about the background as I too remember it working at some stage and the code is unchanged for rather a long time.  There are some unexpected effects with text size for multiple characters with the same settings but I'll wait for you to finish adjusting.  Thanks again for looking at this.

**Comment by pjbroad** [comment] 2020-12-02 19:53
I think that's fine, much better than I remember the feature working before.  I like it fixed to name text position and it works fine in instance mode etc.  The only think I'd suggest changing would be perhaps allowing more text rather than truncating, perhaps using multiple lines of text as needed.

**Comment by gvissers** [comment] 2020-12-03 07:41
> The only think I'd suggest changing would be perhaps allowing more text rather than truncating, perhaps using multiple lines of text as needed.
Yeah, the truncation was kept from the existing code. I will probably take a look at it later, see if we can split it into lines instead.

**Comment by gvissers** [comment] 2020-12-04 12:25
> > The only think I'd suggest changing would be perhaps allowing more text rather than truncating, perhaps using multiple lines of text as needed.
> 
> Yeah, the truncation was kept from the existing code. I will probably take a look at it later, see if we can split it into lines instead.

Done.

**Comment by pjbroad** [comment] 2020-12-05 13:09
Much better.  A few points.
- The maximum length is four character short, perhaps due to the text wrapping?  Also there is a #define in chat.h (MAX_TEXT_MESSAGE_LENGTH) that sets the maximum length for input that we should probably use.
- The wrapped text sometimes exceeds the bounds of the bubble background.
- The text is obscured by objects at some zoom levels.  I'm sitting in Portland storage while testing.

**Comment by gvissers** [comment] 2020-12-05 14:37
> Much better. A few points.
> 
>     * The maximum length is four character short, perhaps due to the text wrapping?  Also there is a #define in chat.h (MAX_TEXT_MESSAGE_LENGTH) that sets the maximum length for input that we should probably use.

Yeah that's probably due to the newlines inserted by the wrapping, we should increase the buffer size a bit. I had already tried to use the define, but that leads to a circular include dependency `actors.h -> chat.h -> actors.h`. I'll see if I can reasonably move the define to a common shared include file, or perhaps move the inclusion of `actors.h` in `chat.h` to after the definition of  `MAX_TEXT_MESSAGE_LENGTH`.

>     * The wrapped text sometimes exceeds the bounds of the bubble background.

Right, that shouldn't happen, will investigate. Is it only in the corners, or does it really go over the side of the bubble? 

>     * The text is obscured by objects at some zoom levels.  I'm sitting in Portland storage while testing.

That is by design. I can draw the bubbles on top, but IMHO if the corresponding actor is occluded, those disassociated bubbles look very strange. Besides, I don't imagine people use the overhead text as their primary method of following local chat. But if you prefer, I can move the bubbles up front.

**Comment by pjbroad** [comment] 2020-12-07 22:55
Wow, I wish I'd not mentioned the #define now.  The text exceeding the bubble background is not just the corners.  I was testing use this text "The enhanced actor structure holds information about the actors extensions such as if the actor is wearing any armour, weapons etc. abcdefghijklmnopqrstuvwxyz01".

**Comment by gvissers** [comment] 2020-12-08 09:21
> Wow, I wish I'd not mentioned the #define now. 

I agree that it was a bit more reorganization than the use single `#define` might warrant. But I also think it has made the code a bit more robust: the `check_harvesting_effect()` function had nothing at all to do with text handling, code that only needs to process text no longer needs to include all of the eye candy headers. Similarly, the map editor does not use actors, getting rid of the unneeded dependency allows us to change code in that area more easily without breaking the map editor.

>  It looks to be scale dependant and I see the problem with a scale of 1.3.

Thanks for the debug info, I think I have found the problem. Rounding of individual character widths when scaling a text leads to the total width not being simply equal to scaling the original width. I did think of this before, but did not expect the effect to be so large. Oh well. It was not necessarily scale dependant, I think the problem might have occurred with other actors at different distances as well, even if the font scaling factor was an integer.

We may still need to decide de depth at which we draw the text bubbles. As is, they are obscured by objects in front of the bubble, which can be annoying. Drawing them on top of everything can make bubbles appear for actors that are obscured, which looks strange IMHO. On the other hand, you might be less likely to miss what someone is saying. I don't know which option is less bad, let me know if you have a preference.

**Comment by pjbroad** [comment] 2020-12-08 18:37
With the latest changes, this looks well fixed.  Thanks for the work that you've put into fixing what appeared to be a simple bug.  As for the depth, like you say, neither approach is completely satisfying though perhaps the way it is currently is more as you'd expect.  I'd say leave it as it is and see if there are any comments.  If you concur, we should close this issue.

**Comment by gvissers** [comment] 2020-12-08 19:18
> and see if there are any comments.

I highly doubt it :laughing: 

> If you concur, we should close this issue.

All right, closing.

**Closed by gvissers** 2020-12-08 19:18 UTC
Labels: bug, enhancement
