### ISSUE TITLE
Ranging exp/arrow momentarily inaccurate

### ISSUE THREAD

**Issue by gamil-zirak** [raduprv/Eternal-Lands#146] opened 2021-08-17 19:19 UTC
When ranging, the exp/arrows calculation is sometimes too high.  I believe this is caused by a delay between the SEND_PARTIAL_STAT message and the MISSILE_FIRE_A_TO_* messages so that the total number of arrows count is short against the ranging experience.

For both screenshots below, the accurate exp/arrows figure should be 34.

![xp_per_arrow_nosync](https://user-images.githubusercontent.com/77200694/129786706-0efdc2c5-022e-4154-a5f5-e5ff90039519.png)

![xp_per_arrow_sync](https://user-images.githubusercontent.com/77200694/129786460-e8cc7d24-7b44-4055-9a22-917112fd629e.png)

A fix is in pull request #145.

**Comment by gvissers** [comment] 2021-08-19 12:30
I'm sure you the proposed fix is correct, but I'm less certain I understand the root cause.

If the cause is indeed a delay between the handling of the SEND_PARTIAL_STAT message and the MISSILE_FIRE_A_TO_* message (which is not outside the realm of possibility: the second message places an action on the actor queue, which is only processed after previous actions have finished, while the stats are updated immediately), the wrong rate should only be shown for a moment until the animation is performed, right? [Of course, this is the moment that I realize that your issue title contains the word "momentarily" :facepalm: ]

If that's the case, then 
- Good find!
- I think your fix is correct, and we should merge it. `range_exp_at_shot` could be static though, it isn't used outside missiles.c.

**Comment by gamil-zirak** [comment] 2021-08-19 13:26
Thanks for reviewing this. Yes, the exp/arrows is only innacurate for a short time and will change to the correct figure after the animation is performed. It's not a big issue but was certainly noticeable when I was ranging and it wasn't too difficult to get a screenshot of it.

I commited a change to make range_exp_at_shot static. Thanks for pointing that out.

**Comment by gvissers** [comment] 2021-08-19 13:31
Merged, thanks!

**Closed** 2021-08-19 17:32 UTC
